---
- hosts: localhost
  gather_facts: true
  collections:
    - ibm.cloudcollection

  environment:
    IC_API_KEY: "{{ ic_api_key }}"

  pre_tasks:
    - name: Set playbook name var
      set_fact:
        current_playbook_name: "prepare_sno_install"
       
  roles:
 
    - role: validate_parms
      when: vars_validated is not defined 
    - role: check_playbook_complete 
    - role: get_floating_ip_address
      when: (fip is not defined or fip.address is not defined) and not playbook_completion_state == "complete"   
    - role: prepare_sno_install
      when: not playbook_completion_state == "complete"   

  post_tasks:
    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ fip.address }}"
        ansible_user: root
        groups: kvm_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no 
      when: fip.address not in groups['kvm_vsi'] | default([]) and not playbook_completion_state == "complete"   

- hosts: kvm_vsi
  gather_facts: false
  become: yes
  vars:
    ansible_ssh_private_key_file: "auth/{{ name_prefix }}-local-id_rsa"
    ansible_python_interpreter: "/usr/bin/python3"

  pre_tasks:
    - name: Get playbook_completion_state from previous play
      set_fact:
        playbook_completion_state: "{{ hostvars['localhost']['playbook_completion_state'] }}"
     
    - name: Get download_url from previous play
      set_fact:
        download_url: "{{ hostvars['localhost']['download_url'] }}"
      when: not playbook_completion_state == "complete"     

  roles:
    - role: create_sno_vm
      when: not playbook_completion_state == "complete"   
  
  post_tasks:
    - name: Success message
      debug:
        msg: "Your SNO cluster is ready to install"
      when: not playbook_completion_state == "complete"   

- hosts: localhost
  gather_facts: true

  roles:
    - role: start_sno_install
      when: not playbook_completion_state == "complete"   
    - role: set_playbook_complete
      when: not playbook_completion_state == "complete"  

  post_tasks:
    - name: Success message
      debug:
        msg: "Your SNO install started successfully !"
      when: not playbook_completion_state == "complete"   

        